### ISSUE TITLE
Release version 1.5.1.0 via NuGet

### ISSUE THREAD

**Issue by kroimon** [jagregory/fluent-nhibernate#294]
Would be great to get a build of 1.5.1.0 on NuGet, matching the available NHibernate 3.4.0.4000 release.

**Comment by chester89** [comment]
[this] (https://www.nuget.org/packages/FluentNHibernate.Net35) does not work for you?

**Comment by kroimon** [comment]
I'm sorry, I didn't know this is a separate package now. Is that documented anywhere?

**Comment by chester89** [comment]
I'm afraid not, that needs to change

**Comment by chester89** [comment]
Updated [readme] (https://github.com/jagregory/fluent-nhibernate/commit/cccb58de3b98d5b83fabe3fa40f2e41edc35733e), thanks
