### ISSUE TITLE
Missing CommonAssemblyInfo.cs

### ISSUE THREAD

**Issue by rhurlbut** [jagregory/fluent-nhibernate#301]
The current source for v2.0.1 is missing \src\CommonAssemblyInfo.cs file when trying to build the FluentNHibernate.sln solution. This file is a dependency for the FluentNHibernate project and the FluentNHibernate.Testing project.

**Comment by rhurlbut** [comment]
This may have been intentional. I noticed the NHibernate project also doesn't check in the AssemblyInfo.cs file. Thie FluentNHibernate project did check in the file in the past (I had an older one and re-used that). Does anyone know if this is just left out intentionally now? Thank you.

**Comment by jagregory** [comment]
AFAIK, this file is built by the FNH build scripts. It was never (or never
intended to be) checked in to source control.

On Fri, Feb 6, 2015 at 11:07 AM, Robert Hurlbut <notifications@github.com>
wrote:

> This may have been intentional. I noticed the NHibernate project also
> doesn't check in the AssemblyInfo.cs file. Thie FluentNHibernate project
> did check in the file in the past (I had an older one and re-used that).
> Does anyone know if this is just left out intentionally now? Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/301#issuecomment-73157098>
> .
>



-- 
James Gregory

Tel: +61 (0) 411 619 513
Website: http://jagregory.com
Twitter: @jagregory <http://twitter.com/jagregory>

**Comment by rhurlbut** [comment]
Thank you - makes sense. I'll mark as closed.
