### ISSUE TITLE
Fluent NHibernate V2.0.1 types are not CLS compliant

### ISSUE THREAD

**Issue by RobertGammon** [jagregory/fluent-nhibernate#303]
My first issue on GitHub - sorry if this isn't the right forum for it.

The assembly `FluentNHibernate` V2.0.1 is not marked CLS Compliant. V1.4 was.

Is this an oversight? If the file `src\CommonAssemblyInfo.cs` is generated by build tools (I downloaded the source and it isn't there) then should those tools add a `CLSCompliant` attribute, or are the types genuinely no longer CLS compliant?

When I update `FluentNhibernate` to V2.0.1, my builds raise warnings that my CLS-compliant types that depend on it cannot be CLS compliant.

**Comment by chester89** [comment]
Sounds like you're right, let me look into it. If that's true, will be fixed in next release - I'm planning on rolling out some minor fixes soon.
