### ISSUE TITLE
FluentNHibernate.dll does not represent a strongly named assembly

### ISSUE THREAD

**Issue by kevinlow1926** [jagregory/fluent-nhibernate#305]
Hi,

I got the latest version of FluentNHibernate 2.0.1.0 from nuget for a Web application and I would like to just copy the dll to the bin folder and run it with the latest version of NHibernate without updating my other dlls which references FluentNHibernate  1.2.0.712. These other dlls are shared across multiple projects so I would like to keep them the same until we are ready to upgrade. Without the publicKeyToken="8aa435e3cb308880" I can't redirect all references to the new version of the FluenNHibernate.dll. The publickey token is in version 1.2.0.712 but not in version 2.0.1.0. 

Here is what I put in my web.config to redirect to the newer version of FluentNHibernate:

  &lt;runtime>
    &lt;assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      &lt;dependentAssembly>
        &lt;assemblyIdentity name="Iesi.Collections" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
        &lt;bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      &lt;/dependentAssembly>
      &lt;dependentAssembly>
        &lt;assemblyIdentity name="NHibernate" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
        &lt;bindingRedirect oldVersion="0.0.0.0-4.0.0.4000" newVersion="4.0.0.4000" />
      &lt;/dependentAssembly>
      &lt;dependentAssembly>
        &lt;assemblyIdentity name="FluentNHibernate" publicKeyToken="8aa435e3cb308880" culture="neutral" />                                                                  
        &lt;bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="2.0.1.0" />
      &lt;/dependentAssembly>
    &lt;/assemblyBinding>
  &lt;/runtime&gt;

Thanks,
Kevin

**Comment by chester89** [comment]
My position is that Fluent NHibernate won't be strong named. I should really document that one
