### ISSUE TITLE
Cannot build due to missing CommonAssemblyInfo.cs

### ISSUE THREAD

**Issue by brainbolt** [jagregory/fluent-nhibernate#308]
Downloading the source, opening the VS solution, and attempting to build the solution as described in the [Getting the source](https://github.com/jagregory/fluent-nhibernate/wiki/Getting-started#getting-the-source) section of the Getting Started page of the wiki results in a failure due to a missing file 'CommonAssemblyInfo.cs' in the FluentNHibernate and FluentNHibernate.Testing projects. 

I found the same problem described in issue https://github.com/jagregory/fluent-nhibernate/issues/301, which is closed, but offers no solution.

**Comment by brainbolt** [comment]
The build succeeds if you update the project files to remove the references to the non-existent file.

**Comment by jagregory** [comment]
That file is generated the build scripts, like the other issue says. Run
build.bat.

It's better if you use the releases published to nuget when possible.

On Saturday, 21 March 2015, Brandon Rainbolt <notifications@github.com>
wrote:

> The build succeeds if you update the project files to remove the
> references to the non-existent file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/308#issuecomment-84171381>
> .
>


-- 
James Gregory

Tel: +61 (0) 411 619 513
Website: http://jagregory.com
Twitter: @jagregory <http://twitter.com/jagregory>

**Comment by chester89** [comment]
@jagregory is right. CommonAssemblyInfo is needed, but you need to invoke build script first.

**Comment by ivaylo5ev** [comment]
It would be nice if some documentation is explicitly explaining how to properly set up the project when downloaded from git. A good place is a brief step-by-step instruction in the readme, contributions section. Contributors-Readme!.txt is also a nice place for that.

It is not obvious to know you need to run the Build.bat to get the project fixed and suitable for work in an IDE, and it is also good to know to have Rake pre-installed to run the Build.bat. Contributors-Readme!.txt is also a nice place for that.

I believe it would safe a lot of time and would not turn down would-be contributors.

**Comment by chester89** [comment]
Fair enough, I'll do so

2015-09-01 19:22 GMT+03:00 Ivaylo Slavov <notifications@github.com>:

> It would be nice if some documentation is explicitly explaining how to
> properly set up the project when downloaded from git. A good place is a
> brief step-by-step instruction in the readme, contributions section.
> Contributors-Readme!.txt is also a nice place for that.
>
> It is not obvious to know you need to run the Build.bat to get the project
> fixed and suitable for work in an IDE, and it is also good to know to have
> Rake pre-installed to run the Build.bat. Contributors-Readme!.txt is also a
> nice place for that.
>
> I believe it would safe a lot of time and would not turn down would-be
> contributors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/308#issuecomment-136780687>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by ivaylo5ev** [comment]
Great, I appreciate that :)

**Comment by majjihari** [comment]
Remove the file from properties in solution explorer and it will work
