### ISSUE TITLE
Mapping a <timestamp> attribute

### ISSUE THREAD

**Issue by krasilies** [jagregory/fluent-nhibernate#311]
Currently, there is no way using FNH to generate <timestamp> nhibernate xml mapping tag. A workaround invovles creating an interceptor or a DB trigger

**Comment by chester89** [comment]
Sorry for the delay - can you explain what exactly are you trying to do?

**Comment by krasilies** [comment]
hi,

in nhiberbate mapping i can use <timestamp> attribute which will generate
the persist time of the entity.

i'm adding a link to a thread i posted at stackoverflow:
http://stackoverflow.com/questions/30163187/persisting-datetime-when-saving-updating-entities-in-fluent-nhibernate/30177486#30177486

cheers

**Comment by chester89** [comment]
May be [first answer to this] (http://stackoverflow.com/questions/2459765/how-to-make-nhibernate-automatically-change-an-updated-column) can help? But it's still a property, not a timestamp - if I recall correctly, timestamp is for version/concurrency management

**Comment by krasilies** [comment]
you should read the comments of that answer.
i need to log insert/update datetime for auditing, not for versioning.

**Comment by chester89** [comment]
Apologies - I meant the second answer. generated=always works for
properties too, not only for version columns

2015-06-04 12:39 GMT+03:00 krasilies <notifications@github.com>:

> you should read the comments of that answer.
> i need to log insert/update datetime for auditing, not for versioning.
> On 4 Jun 2015 12:36, "Gleb Chermennov" <notifications@github.com> wrote:
>
> > May be first answer to this
> > <
> http://stackoverflow.com/questions/2459765/how-to-make-nhibernate-automatically-change-an-updated-column
> >
> > can help? But it's still a property, not a timestamp - if I recall
> > correctly, timestamp is for version/concurrency management
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jagregory/fluent-nhibernate/issues/311#issuecomment-108808401
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/311#issuecomment-108808830>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by krasilies** [comment]
generate always doesn't work - still getting null in that column (read the
single comment there by BlueBird)
as corey coogan suggsted, i used an event listenet

**Comment by chester89** [comment]
​have you tried setting insert/update attribute to true?​

2015-06-04 12:57 GMT+03:00 krasilies <notifications@github.com>:

> generate always doesn't work - still getting null in that column (read the
> single comment there by BlueBird)
> as corey coogan suggsted, i used an event listenet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/311#issuecomment-108815055>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by krasilies** [comment]
yes, i think its really simple to replicate the problem

**Comment by krasilies** [comment]
Hi jagregory/fluent-nhi,

I'd like to add you to my professional network on LinkedIn.

- Gilad

Confirm that you know Gilad: https://www.linkedin.com/e/v2?e=0-ikycw1oc-bp&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=3Nb8HRY5&invitationId=6107608348394348544








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ikycw1oc-bp&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF0CJ0zrvzBEAAAAVMKZRvbsXar2OxDS49cjPE_5xY6j5TDvA8KhYcoNlCNo5Mvi7yB8WxJtceKqoS8S9FrwxYcAPe1_a3mxSTPpPtI67ALDc3xQJ4BYG5CGg9Z97JTfFymTYh1UUuMCZN7DRxx8K0T9yudcnVpXbvDge0cuM40DZ5Hdiwl170Rc6mAZbaCv5Jq&eid=0-ikycw1oc-bp


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ikycw1oc-bp&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by krasilies** [comment]
Hi jagregory/fluent-nhi,

I'd like to add you to my professional network on LinkedIn.

- Gilad

Confirm that you know Gilad: https://www.linkedin.com/e/v2?e=0-ikycw0p6-gl&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=vYbnRrO7&invitationId=6107608348541153281








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ikycw0p6-gl&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEjB3hiVfvK9gAAAVMKZUOUENn1Fa0RkJZC7nDZVXUc9Db1jLbQOsjrygrd0XV_PMuaK6qxvafKtZAPFpJxSgabDeGAo2Jq_Fga0M1BRM3iXDWyMW8CM8pIYT8TxqjMKqwK8s-QtI3IJtkZW2iZzZyjljSs5QCQHjmVecO2mhtQs2UFSEi7xbpFHuk6knvZQX1C&eid=0-ikycw0p6-gl


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ikycw0p6-gl&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by krasilies** [comment]
Hi jagregory/fluent-nhi,

I'd like to add you to my professional network on LinkedIn.

- Gilad

Confirm that you know Gilad: https://www.linkedin.com/e/v2?e=0-ikycw07l-lf&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=qE7mwr1-&invitationId=6107608348679557121








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ikycw07l-lf&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH04UAE9XKxJgAAAVMKZpqgSlbJ08bxVpTlwiWL9nEiePxm2qexA85TNVOHisyGTsyWPhXgBGcuVu2WnHCIRbD5CtpSYWFlDHItozddd5OmLgZeA5HCeMMzs_BBmUKHVKNCV-_CGPqXdBlnh63SaRCtb_sVhYtNUinOwomy2NKQQ5HSkPYY_2AXG9tpJv1P3RPQ&eid=0-ikycw07l-lf


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ikycw07l-lf&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by krasilies** [comment]
Hi jagregory/fluent-nhi,

I'd like to add you to my professional network on LinkedIn.

- Gilad

Confirm that you know Gilad: https://www.linkedin.com/e/v2?e=0-ikycw03n-84&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=D2g0Y_y8&invitationId=6107608348822167552








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ikycw03n-84&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF7sTTpMlxO6gAAAVMKZqN0Ty3marZd_VlZCVl2BkTfKNWRkvcj6C-9Y467gzNuY8wRPIb0S7a9Hzkq8pAVJd4JIcGVVyicxW_W8DufT_ZOcJXCGIh2a9NepY6nUP2mlcm-vPnwgKaoPGA2nCfFQ4SUAcqQb_BRgffsP2Ufrc5QZKpaUHU185OJNa6Rx-tY5kdC&eid=0-ikycw03n-84


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ikycw03n-84&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by krasilies** [comment]
Gilad Segal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-613248-il7s1x2p-mb&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=D2g0Y_y8&invitationID=6107608348822167552

View Gilad Segal&#39;s profile: https://www.linkedin.com/e/v2?e=-613248-il7s1x2p-mb&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=D2g0Y_y8&invitationID=6107608348822167552





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-613248-il7s1x2p-mb&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-613248-il7s1x2p-mb&loid=AQHMpWkYjDhChQAAAVMtVmvy1jA1eMidQ5aEtnyLDuaa35mLcpGRB50I90R74SssTjRoNdZK-FUo8WASXaN0CFWxQTgIQvus48q2wPXCdo0rj6HrhcWPJD4NaYzpIsJkZsHVGVRe6AhxJqYkZard4B7cH6w1fvEp4tcXhflQyHxcCGhHXaqJUghvFlfiCe6cWf9u

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-613248-il7s1x2p-mb&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by krasilies** [comment]
Gilad Segal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=qo4hz9-il7s1w9g-hv&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=3Nb8HRY5&invitationID=6107608348394348544

View Gilad Segal&#39;s profile: https://www.linkedin.com/e/v2?e=qo4hz9-il7s1w9g-hv&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=3Nb8HRY5&invitationID=6107608348394348544





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=qo4hz9-il7s1w9g-hv&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=qo4hz9-il7s1w9g-hv&loid=AQGWcvQ_8hZbWgAAAVMtVt-phC1BE-qIVp6fKvLWfaGAQwlHpdVTxtg6-zo1MnjiewUVzjm85utOsGAk7ImRPXzG2tFz_Sf_lOgIE2YVYxwdK81lhU5w4Dz0-yD_o1761B0s-yIqBW9NeZ90OocVkeY-hIFJVbqz4RnmOj93nhEUQDEqoNVAQpbBjtHfSYchrqDN

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=qo4hz9-il7s1w9g-hv&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by krasilies** [comment]
Gilad Segal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-xpn139-il7s2fu8-uy&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=qE7mwr1-&invitationID=6107608348679557121

View Gilad Segal&#39;s profile: https://www.linkedin.com/e/v2?e=-xpn139-il7s2fu8-uy&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=qE7mwr1-&invitationID=6107608348679557121





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-xpn139-il7s2fu8-uy&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-xpn139-il7s2fu8-uy&loid=AQFXMbaQt8Z4igAAAVMtWHIdi9JgU_ewJWpUaOiUSjU9SpBy9-f9Aah49g59ZMY1f8tpp0PAzn1YTgtLzKjaZTI2ScvhZk66S97aA66sa452tVdJjFXx8nyr__jYjyS-Z2TFrC1MUshxHeqJbqbFowOLYuqGiRv5SZBaYAvnrZnJbWfcIV3d1KpPSMp5ooloBglv

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-xpn139-il7s2fu8-uy&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by krasilies** [comment]
Gilad Segal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=vYbnRrO7&invitationID=6107608348541153281

View Gilad Segal&#39;s profile: https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=vYbnRrO7&invitationID=6107608348541153281





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-f23d3c-il7s2fun-d&loid=AQHaapvyeToRNgAAAVMtWz_uyWu4YZcDGFu447yYFCV3743H899nBYCt9jaeJCn-ZMl1agnBCfggaWrBJy_xH2cJgWVYisv1bk__S9FXRQHcj9te9vygNCgWWDQmO5g05IEPaGWrq2IV4LXXnXNDcIaFme3m6xZ4MH8Qehh2VMUBXlMTF2nxROp5OG4apx2jL-P2

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chester89** [comment]
@krasilies someone hacked your account? feel free to reopen when you get
rid of spam

2016-02-29 17:07 GMT+03:00 krasilies <notifications@github.com>:

> Gilad Segal would like to connect on LinkedIn. How would you like to
> respond?
>
> Accept:
> https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=vYbnRrO7&invitationID=6107608348541153281
>
> View Gilad Segal&#39;s profile:
> https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=vYbnRrO7&invitationID=6107608348541153281
>
>
>
>
>
> You received an invitation to connect. LinkedIn will use your email
> address to make suggestions to our members in features like People You May
> Know. Unsubscribe here:
> https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-f23d3c-il7s2fun-d&loid=AQHaapvyeToRNgAAAVMtWz_uyWu4YZcDGFu447yYFCV3743H899nBYCt9jaeJCn-ZMl1agnBCfggaWrBJy_xH2cJgWVYisv1bk__S9FXRQHcj9te9vygNCgWWDQmO5g05IEPaGWrq2IV4LXXnXNDcIaFme3m6xZ4MH8Qehh2VMUBXlMTF2nxROp5OG4apx2jL-P2
>
> This email was sent to reply@reply.github.com.
>
> If you need assistance or have questions, please contact LinkedIn Customer
> Service:
> https://www.linkedin.com/e/v2?e=-f23d3c-il7s2fun-d&a=customerServiceUrl&ek=first_guest_reminder_01
>
>
> &copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA
> 94043. LinkedIn and the LinkedIn logo are registered trademarks of
> LinkedIn.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/311#issuecomment-190224928>
> .
>



-- 
Yours faithfully,
Gleb
