### ISSUE TITLE
HasMany pairs to wrong ManyToOne relationships

### ISSUE THREAD

**Issue by timbussmann** [jagregory/fluent-nhibernate#315]
When having `HasMany(...)` configurations on an entity map and multiple (ManyToOne) references to this entity, the RelationshipPairingVisitor sometimes matches the OneToMany mappings to the wrong ManyToOne mappings.

This issue arises from the PairOneToManys implementation on the RelationshipPairingVisitor. The implementation orders the mappings by name and then selects the first ManyToOneMapping which targets the entity containing the `HasMany(...)` configurations. Depending on the namings, this results in the wrong mappings set to the `OtherSide` properties since all ManyToOne mappings to this entity match this condition.

Especially when using custom `IHasManyConvention` for the foreign key conventions, receiving the wrong mappings results in creating faulty and very confusing database schemas.

I have written a test reproducing the described behaviour. If required, I can also provide a sample project.

**Comment by timbussmann** [comment]
see [here](https://github.com/timbussmann/fluent-nhibernate/commit/bdfc176db6f7dae01673a48a19f5634b138ed4c0) for the mentioned test. I can create a PR if you like.

**Comment by chester89** [comment]
Is this the same as https://github.com/jagregory/fluent-nhibernate/pull/313? If so, the fix should arrive until the weekend

**Comment by timbussmann** [comment]
Yes you're right. I didn't see #313. Sorry for the duplicate.

**Comment by chester89** [comment]
No worries
