### ISSUE TITLE
000webhost as Server Mysql

### ISSUE THREAD

**Issue by johnjake** [jagregory/fluent-nhibernate#317]
Hey! im having problem using Fluent-NHibernate configuration Im always getting an error of An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

private static void InitializeSessionFactory()
        {
            _sessionFactory = Fluently.Configure()
                        .Database(MySQLConfiguration.Standard.ConnectionString("Server=mysql8.000webhost.com; Database=a8347166_love; Uid=xxxx; Pwd=xxxx;"))
                            .Mappings(m => m.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()))
                               .BuildSessionFactory();
        }

**Comment by chester89** [comment]
So what does inner exceptions say?

**Comment by johnjake** [comment]
Could not create the driver from NHibernate.Driver.MySqlDataDriver, NHibernate, Version=4.0.0.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4.   

Im trying to connect to Database (MySQL) from my remote host is this possible? to used online hosting as database server?

**Comment by chester89** [comment]
Of course it's possible, people do it all the time - host their app on
computer A and their db on computer C.
Please send me the code the sets up an ISession (without the connection
string) - I'll have a look. If not on Github, you know my email.
But I can't promise fast response - two days at least.

2015-08-13 8:01 GMT+03:00 johnjake <notifications@github.com>:

> Could not create the driver from NHibernate.Driver.MySqlDataDriver,
> NHibernate, Version=4.0.0.4000, Culture=neutral,
> PublicKeyToken=aa95f207798dfdb4.
>
> Im trying to connect to Database (MySQL) from my remote host is this
> possible? to used online hosting as database server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/317#issuecomment-130536298>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by Beatles1692** [comment]
It more seems a missing dll problem to me.Please make sure that you are
using Nhibernate 4.0.0.4000. You should check the version of Nhibernate.dll
in your bin directory. Sometimes it is possible that you are referencing
different versions of NHibernate in different projects and thus a wrong
version is copied into bin directory.

**Comment by chester89** [comment]
That's another opportunity, yes. Because I always run tests before
releasing on latest NHibernate version and never had such problems.

2015-08-13 11:20 GMT+03:00 Beatles1692 <notifications@github.com>:

> It more seems a missing dll problem to me.Please make sure that you are
> using Nhibernate 4.0.0.4000. You should check the version of Nhibernate.dll
> in your bin directory. Sometimes it is possible that you are referencing
> different versions of NHibernate in different projects and thus a wrong
> version is copied into bin directory.
>
> On Thu, Aug 13, 2015 at 12:17 PM, Gleb Chermennov <
> notifications@github.com>
> wrote:
>
> > Of course it's possible, people do it all the time - host their app on
> > computer A and their db on computer C.
> > Please send me the code the sets up an ISession (without the connection
> > string) - I'll have a look. If not on Github, you know my email.
> > But I can't promise fast response - two days at least.
> >
> > 2015-08-13 8:01 GMT+03:00 johnjake <notifications@github.com>:
> >
> > > Could not create the driver from NHibernate.Driver.MySqlDataDriver,
> > > NHibernate, Version=4.0.0.4000, Culture=neutral,
> > > PublicKeyToken=aa95f207798dfdb4.
> > >
> > > Im trying to connect to Database (MySQL) from my remote host is this
> > > possible? to used online hosting as database server?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/jagregory/fluent-nhibernate/issues/317#issuecomment-130536298
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Yours faithfully,
> > Gleb
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jagregory/fluent-nhibernate/issues/317#issuecomment-130567100
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/317#issuecomment-130572313>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by johnjake** [comment]
using FluentNHibernate.Cfg;
using FluentNHibernate.Cfg.Db;
using MySql.Data.MySqlClient;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace EMS
{
    public class NHibernateHelper
    {
          private static ISessionFactory _sessionFactory;
        private static readonly object factorylock = new object();
        public static ISessionFactory SessionFactory
        {
            get
            {
                if (_sessionFactory == null)
                    InitializeSessionFactory();
                return _sessionFactory;
            }
        }
        private static void InitializeSessionFactory()
        {
            _sessionFactory = Fluently.Configure()
                .Database(MySQLConfiguration.Standard.ConnectionString("Server=mysql8.000webhost.com; Database=a8347166_love; Uid=a8347166_love; Pwd=livelove_2000;"))
                .Mappings(m => m.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()))
                .BuildSessionFactory();
        }

        public ISession OpenSession()
        {
            return SessionFactory.OpenSession();
        }
        public bool SessionStatus() 
        {
            if (SessionFactory.IsClosed)
            {
                return false;
            }
            else { return true; }
        }
    }
    
}

**Comment by johnjake** [comment]
@Beatles1692  I works perfectly using MS-SQL Server 2012, and I have DO (Digital Ocean) account so I was wondering if it support using mysql VPN. The version that I been using is from Visual Studio NuGet 
![version](https://cloud.githubusercontent.com/assets/4056983/9263503/7f0522b8-41d2-11e5-8cb2-ccbf9e9b7a86.png)

**Comment by Beatles1692** [comment]
There is one other possibility that you should download and use MySQL ado.net data connector: https://dev.mysql.com/downloads/connector/net/

-----Original Message-----

**Comment by johnjake** [comment]
@Beatles1692 actually I already installed it. and attach the dll reference to my project 
![mysql](https://cloud.githubusercontent.com/assets/4056983/9267305/7b126006-4201-11e5-8672-2fd42385b571.png)

**Comment by johnjake** [comment]
@Beatles1692  actually I tried other server and it works the problem was the 000webhost.com host restriction.

**Comment by chester89** [comment]
So problem solved then?

2015-08-14 9:01 GMT+03:00 johnjake <notifications@github.com>:

> @Beatles1692 <https://github.com/Beatles1692> actually I tried other
> server and it works the problem was the 000webhost.com host restriction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/317#issuecomment-130983129>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by johnjake** [comment]
@chester89 yap thanks a lot :D I really appreciate it, I dont get much help for C# Fluent Nhibernate at stackoverflow. I really love fluent than NHibernate as I hate, I always code for xml, thank you for your efforts and contribution hope the fluent community support will grow. Thanks a lot man :D
