### ISSUE TITLE
[Solved] Cascading while deleting does not work

### ISSUE THREAD

**Issue by Daviziu** [jagregory/fluent-nhibernate#325]
Hi
I'm not entirely sure if it is a problem of Fluent-NHibernate or if I implemented something wrong, but I can't seem to fix my problem.

I have 3 entities: `CostumerGroup`, `Customer` and `Report`. They're linked with 2 one-to-many associations in the following way:

One `CustomerGroup` has many `Customer`s
One `Customer` has many `Report`s

My entity and mapping classes look like this (I deleted some unnecessary code):

```csharp
public class CustomerGroup
   {
      public virtual int Id { get; protected set; }
      public virtual IList<Customer> Customers { get; protected set; }

      public virtual void DeleteCustomer(Customer customer)
      {
         this.Customers.Remove(customer);
      }
      [...]
   }

 public class CustomerGroupMap : ClassMap<CustomerGroup>
   {
      public CustomerGroupMap()
      {
         Id(x => x.Id);
         HasMany<Customer>(x => x.Customers)
            .Cascade.All();
      }
   }

 public class Customer
   {
      public virtual int Id { get; protected set; }
      public virtual IList<Report> Reports { get; protected set; }
      public virtual CustomerGroup CustomerGroup { get; set; }

      public virtual void DeleteReport(Report report)
      {
         this.Reports.Remove(report);
      }
      [...]
   }

public class CustomerMap : ClassMap<Customer>
   {
      public CustomerMap()
      {
         Id(x => x.Id);

         References<CustomerGroup>(x => x.CustomerGroup);
         HasMany<Report>(x => x.Reports)
            .Cascade.All();
      }
   }

 public class Report
   {
      public virtual Customer Customer { get; set; }
   }

public class ReportMap : ClassMap<Report>
   {
      public ReportMap()
      {
         Id(x => x.Id);
         References<Customer>(x => x.Customer);
      }
   }

```

Everything works fine while creating and saving the entities to the database.

So, I am able to delete Report entities, but I am not able to delete Customer entities, even though I do it in a similar manner. The error text is:
> deleted object would be re-saved by cascade (remove deleted object from associations)

I deleted the entities in the following way (simplified code):
```csharp
[...]
Report report = //code for getting a persistent report entity
report.Costumer.DeleteReport(report);
session.Delete(report); // this one works fine
 
Customer customer = //code for getting a customer
customer.CustomerGroup.DeleteCustomer(customer);
session.Delete(customer); // doesn't work

transaction.Commit()
[...]
```
I even tried removing all references of `customer` and cleared the `Reports` property before deleting it, but the result is still the same.

Help would be very much appreciated

**Comment by Daviziu** [comment]
Found the problem myself. It was indeed a mistake I made.

Using `.Cascade.AllDeletaOrphan()` instead of `.Cascade.All()` solved my problem.
I thought `All` would include the behaviour I was anticipating

**Comment by chester89** [comment]
I'm glad it all worked out
