### ISSUE TITLE
2.0.2 assembly version

### ISSUE THREAD

**Issue by i4004** [jagregory/fluent-nhibernate#328]
I noticed what 2.0.2 package has actual assembly version of 1.5.2, is this correct?
And also possibly wrong assembly title.
![screenshot](https://cloud.githubusercontent.com/assets/5744532/10298547/21b08f26-6c02-11e5-8907-488fc16f8a24.PNG)

**Comment by chester89** [comment]
It's not, thanks for the catch. I'll upload new versions today (with right version numbers)

**Comment by chester89** [comment]
Please take a look at 2.0.3 version

**Comment by i4004** [comment]
Looks ok now! Thanks :)

**Comment by chester89** [comment]
Closing this
