### ISSUE TITLE
obdc connection 

### ISSUE THREAD

**Issue by johnjake** [jagregory/fluent-nhibernate#332]
Hey Good Day to all Fluent Nhibernate

I would like to ask if it is possible to used fluent NHibernate for obdc connection bcoz Dentrix SDK (API) only allow obdc connection. If not possible what is the best way/technique 

Best regards and God Bless 

John Jake

**Comment by chester89** [comment]
It's not something that's built in, but you can do it - take a look at [this SO question](http://stackoverflow.com/questions/5676812/is-it-possible-to-use-fluentnhibernate-with-an-odbc-connection)

**Comment by johnjake** [comment]
in that example i got error in dialect

**Comment by johnjake** [comment]
or how do i customize dialect to create like obdcMyDialect

**Comment by chester89** [comment]
What kind of error? What does the error message say?

2015-11-25 17:36 GMT+03:00 johnjake <notifications@github.com>:

> or how do i customize dialect to create like obdcMyDialect
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/332#issuecomment-159624899>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by johnjake** [comment]
public static OdbcConfiguration MyDialect // <-- insert any name here
        {
            get
            {
                // insert the dialect you want to use
                return new OdbcConfiguration().Dialect<NHibernate.Dialect.MyDialect>();
            }
        }

missing assembly reference MyDialect does not exist

**Comment by johnjake** [comment]
![dialect](https://cloud.githubusercontent.com/assets/4056983/11401102/c4de6168-9345-11e5-8a51-7437b0898106.png)

**Comment by chester89** [comment]
So, what dialect does your data source use?

2015-11-25 18:26 GMT+03:00 johnjake <notifications@github.com>:

> [image: dialect]
> <https://cloud.githubusercontent.com/assets/4056983/11401102/c4de6168-9345-11e5-8a51-7437b0898106.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/332#issuecomment-159640468>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by johnjake** [comment]
the c-treeACE SQL database

**Comment by chester89** [comment]
I'm not familiar with that database

2015-11-25 19:01 GMT+03:00 johnjake <notifications@github.com>:

> the c-treeACE SQL database
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/332#issuecomment-159654928>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by johnjake** [comment]
Sir for the obdc is it possible to just used db2 ? can you give me sample Sir obdc using access or any obdc form maybe it will work. Thanks a lot Sir

**Comment by chester89** [comment]
Frankly, I have no idea

2015-11-27 4:42 GMT+03:00 johnjake <notifications@github.com>:

> Sir for the obdc is it possible to just used db2 ? can you give me sample
> Sir obdc using access or any obdc form maybe it will work. Thanks a lot Sir
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/332#issuecomment-160017360>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by chester89** [comment]
Closing as it seems to be not related to Fluent
