### ISSUE TITLE
Could not create the driver

### ISSUE THREAD

**Issue by 001arthur** [jagregory/fluent-nhibernate#333]
I Have a problem during the execution, I'm getting this message error:
"Additional information: Could not create the driver from NHibernate.Driver.SQLite20Driver, NHibernate, Version=4.0.0.4000, Culture=neutral, PublicKeyToken=aa95f207798dfdb4."

At this part of the code:

new SchemaExport(config).Create(false, true);

I don't what to do

**Comment by chester89** [comment]
Can you post the full stacktrace and your code?

**Comment by 001arthur** [comment]
It's solved, and I'm new in github, and I don't know how to close it.

The problem was that was missing a bar "\" in the ConnectionString

**Comment by chester89** [comment]
I see.
Don't worry, I'll close it

2015-12-22 14:53 GMT+03:00 001arthur <notifications@github.com>:

> It's solved, and I'm new in github, and I don't know how to close it.
>
> The problem was that was missing a bar "\" in the ConnectionString
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/333#issuecomment-166594037>
> .
>



-- 
Yours faithfully,
Gleb
