### ISSUE TITLE
enum types are ignored by AutoMapping

### ISSUE THREAD

**Issue by bartoszkp** [jagregory/fluent-nhibernate#335]
For this simple model:

    public class X { public virtual int Id { get; set; }  public virtual EnumType E { get; set; } }
    public enum EnumType { E1, E2 };

when using automapping functionality:

    AutoMap.AssemblyOf<X>(new MappingConfiguration());

`E` is ignored. `MappingConfiguration` indicates that `EnumType` is a component - perhaps this is the problem, but without it, "missing `Id` property" exception is thrown.

When adding an explicit mapping (`Map(x => x.E);`) everything works as expected.

Related StackOverflow question: http://stackoverflow.com/questions/34667082/why-does-automapping-from-fluents-nhibernate-ignore-an-enum-type

**Comment by chester89** [comment]
Fair point, I will look into that

**Comment by bartoszkp** [comment]
@chester89 Sorry for the confusion, the problem was solved as described in this comment: http://stackoverflow.com/questions/34667082/why-does-automapping-from-fluents-nhibernate-ignore-an-enum-type#comment57213196_34732522 

My `ShouldMap` implementation was flawed, now everything seems to work fine :) Should I close the ticket?

**Comment by chester89** [comment]
I see. Please do

2016-01-12 13:38 GMT+03:00 bartoszkp <notifications@github.com>:

> @chester89 <https://github.com/chester89> Sorry for the confusion, the
> problem was solved as described in this comment:
> http://stackoverflow.com/questions/34667082/why-does-automapping-from-fluents-nhibernate-ignore-an-enum-type#comment57213196_34732522
>
> My ShouldMap implementation was flawed, now everything seems to work fine
> :) Should I close the ticket?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/335#issuecomment-170870431>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by bartoszkp** [comment]
Problem was due to incorrect `ShouldMap` and `IsComponent` implementations. Properties are not components, so `IsComponent` should return `false`, and so should do `ShouldMap` - "map" in this context refers to whole entities, not their properties. 

So despite the fact that `ShouldMap`, roughly speaking, says that an enum should not be "mapped", it will be included in the model, as a property of its parent type.
