### ISSUE TITLE
v2.0.3.0 assembly is not strongly named 

### ISSUE THREAD

**Issue by aliluyko89** [jagregory/fluent-nhibernate#336]
The latest version v2.0.3.0 available via NuGet is not strongly named.
Could you please explain in deep why you don't want sign assembly?
Probably lets create build script which will build two versions of packages?

I have read article <a href="http://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/">FubuMVC Lessons Learned — Strong Naming Woes and Workarounds</a> but I don't see a big problem here.

Based on comments to other versions of your product I think it will be great to have signed package also.

Thanks

**Comment by chester89** [comment]
Ok, this is going to sound harsh, but in my opinion it's not worth time investment. I'd rather make Fluent build on Mono/CoreClr, improve build scripts, write tests for existing features or simple read up on some parts of the code I'm not that familiar with.

**Comment by DogaOztuzun** [comment]
Is there any plan on this subject ?

**Comment by chester89** [comment]
If you're willing to supply working script that alters the solution/project
files and make a PR, I'll take a look. There also will be a separate NuGet
package, of course

2016-01-20 17:43 GMT+03:00 DogaOztuzun <notifications@github.com>:

> Is there any plan on this subject ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/336#issuecomment-173224263>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by chester89** [comment]
That's what I thought

**Comment by maggarwal** [comment]
@chester89 What's the point of having separate nuget package? I am willing to do a PR for strong naming.

**Comment by chester89** [comment]
@maggarwal I'm against it because I don't see the point. @jagregory @jrgcubano what do you think?

**Comment by kalevigit** [comment]
It basically renders your code useless in solutions, that require strong names. 
Because if you want to strong name an assembly that is using FluentNHibernate, then it has to be strong named also. 
So I downloaded the source, and created a strong name, but now its detached from your source :(
