### ISSUE TITLE
Code Contracts complains about uptdated PDB file

### ISSUE THREAD

**Issue by shatl** [jagregory/fluent-nhibernate#337]
Reading assembly 'FluentNHibernate' from 'D:\Work\Sharp-Architecture\Packages\FluentNHibernate.2.0.3.0\lib\net40\FluentNHibernate.dll' resulted in errors.
The pdb associated with D:\Work\Sharp-Architecture\Packages\FluentNHibernate.2.0.3.0\lib\net40\FluentNHibernate.dll is out of date.

Could you please check?

**Comment by chester89** [comment]
Can you give more details on that? I haven't used code contracts for a while. May be post an entire log?

**Comment by shatl** [comment]
Please disregard this. No issues after upgrade to latest CC version.

**Comment by shatl** [comment]
Looks like this is not related to FluentNHibernate.Sorry for disturbing.

**Comment by chester89** [comment]
​I had a feeling it wasn't. Not to worry.​

2016-02-22 23:39 GMT+03:00 Vitaliy K <notifications@github.com>:

> Looks like this is not related to FluentNHibernate.Sorry for disturbing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/337#issuecomment-187373058>
> .
>



-- 
Yours faithfully,
Gleb
