### ISSUE TITLE
Connection leaks with WCF distributed transactions, not thread safe when using async/await keywords in service

### ISSUE THREAD

**Issue by ajtowf** [jagregory/fluent-nhibernate#338]
We're leaking connections when using async/await keywords with distributed transactions in our services, which results in "The current TransactionScope is already complete” exceptions after a while, even from services that don't consume transactions, hence the leak.

- [Blog post with details](http://www.towfeek.se/2016/03/connection-leaks-when-using-asyncawait-with-transactions-in-wcf/)
- [Screencast illustrating the problem](https://www.youtube.com/watch?v=PHLyJSOQmJA)
- [Source code to reproduce](https://github.com/ajtowf/dist_transactions_lab)

**Comment by chester89** [comment]
I think that can be closed. Feel free to reopen if you think that's a problem on Fluent NHibenate side of the fence
