### ISSUE TITLE
Work With Webapi2 And SQL Server,Insert ,Select Work Correctly,Update Delete not Work

### ISSUE THREAD

**Issue by xuxianmei** [jagregory/fluent-nhibernate#339]
When Update Delete transaction commit not Generate any sql , And The next Select return Data from Session Cache.How solve it.
in addition in asp.net mvc I use The Same Interface to Update Data to SQL SERVER work correctly .

**Comment by chester89** [comment]
You'll have to be more specific. Can you share the code that doesn't work? Your config and mappings would be helpful

**Comment by chester89** [comment]
The part that does work would be nice to have

**Comment by xuxianmei** [comment]
Be Sloved with Session.flush

**Comment by chester89** [comment]
So it's solved then? Please close the issue

2016-03-17 9:05 GMT+03:00 xuxianmei <notifications@github.com>:

> Be Sloved with Session.flush
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/fluent-nhibernate/issues/339#issuecomment-197721399>
>



-- 
Yours faithfully,
Gleb
