### ISSUE TITLE
Upgrade to 2.0.3.0 from 1.3.0.717

### ISSUE THREAD

**Issue by xuxianmei** [jagregory/fluent-nhibernate#341]
Any issue should pay attation ?
or Just use nuget install will be ok?
for help.

**Comment by chester89** [comment]
Well, the biggest change is NHibernate 4.x. If you can deal with that, I suspect you'll be fine.

**Comment by xuxianmei** [comment]
@chester89  Get it ! thanks

**Comment by chester89** [comment]
In NHibernate itself - I guess there should be. For Fluent - you can see release notes for each release, we don't roll out very often

**Comment by handcraftsman** [comment]
One breaking change is that prefixes now always cascade to components [#298](https://github.com/jagregory/fluent-nhibernate/pull/298)
There doesn't seem to be a way to configure it NOT to use the prefixes on component fields so you may end up having to rename columns.

**Comment by chester89** [comment]
Closing this, feel free to reopen if you have more questions
