### ISSUE TITLE
FluentNhibernate 2.0.3.0 PublicKeyToken = null

### ISSUE THREAD

**Issue by mbraunwart** [jagregory/fluent-nhibernate#342]
Hello,

I'm not sure how much this is a concern for anyone else, but we happened to have a project where a referenced dll from another project was referencing an older version of FluentNHibernate. When upgrading the current project with the latest version 2.0.3.0 we had issues with this conflict. Typically this is something that a BindingRedirect settles, but when using the Assembly Binding Log Viewer we determined that the Public Key Token was null and the dll unsigned. This of course did not allow us to perform the binding redirect and couldn't get this resolved till we modified the dll that was referencing the previous version of Fluent.

FluentNHibernate, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null

EDIT: I pulled this unsigned version from NuGet

**Comment by chester89** [comment]
I guess I'll have to add a page to the docs that says about strong naming. You can see #336 for my thoughts on this. TLDR - if someone contribute build scripts and maintain a separate Nuget package, I wont be offended.
