### ISSUE TITLE
About #271

### ISSUE THREAD

**Issue by rafakwolf** [jagregory/fluent-nhibernate#346]
I'm using 2.0.3 version, sql server 2014 still doesn't in Fluent Connection configuration.

Thanks

**Comment by chester89** [comment]
@rafakwolf well, as #271 says - at that time (end of 2014) there was no dialect for Sql Server 2014 in NHibernate. As far as I can see, it's still missing. So, until someone contributes it to NH, there's not much we can do on Fluent NHibernate side
