### ISSUE TITLE
http://fluentnhibernate.org is down

### ISSUE THREAD

**Issue by coderjoe** [jagregory/fluent-nhibernate#352]
Not sure where to leave this, so I'll leave it here.

Directed a colleague to your project site a few moments ago by way of the github project description and we discovered the site can't be resolved.

**Comment by chester89** [comment]
Thanks @coderjoe, let me see what I can do

**Comment by jagregory** [comment]
Thanks for noticing this. It was a DNS issue (looks like Github finally decommissioned some old IPs we were pointing to), and the site should be back up as soon as the DNS changes propagate.

**Comment by chester89** [comment]
It's up @coderjoe, thanks @jagregory

**Comment by coderjoe** [comment]
Thanks for the quick fix! :+1:
