### ISSUE TITLE
CommonAssemblyInfo

### ISSUE THREAD

**Issue by ASalihov** [jagregory/fluent-nhibernate#374]
There is no ..\CommonAssemblyInfo.cs
Can somebody upload it?
Thanks

**Comment by ASalihov** [comment]
Ok, I find issue where people say that you need to run Build.bat
But I can'd find that file too.
Can anybody help?

**Comment by jagregory** [comment]
Building instructions: https://github.com/jagregory/fluent-nhibernate/wiki/Building
